// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt5_t-O4NHbzGt1WNp0zbpq-TZzM7rPjY',
    appId: '1:699424596579:web:60bd2e47cd9ff1f7ac4e56',
    messagingSenderId: '699424596579',
    projectId: 'keeapp-bd4e3',
    authDomain: 'keeapp-bd4e3.firebaseapp.com',
    storageBucket: 'keeapp-bd4e3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzeyFtXpTXcuN1aOX7y1ZF5af2Qf6-qso',
    appId: '1:699424596579:android:ab703f6f9937973aac4e56',
    messagingSenderId: '699424596579',
    projectId: 'keeapp-bd4e3',
    storageBucket: 'keeapp-bd4e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlz4FAxteGTOaky8bPeyZ6XhqAzl4R8X0',
    appId: '1:699424596579:ios:611f6ee288948c85ac4e56',
    messagingSenderId: '699424596579',
    projectId: 'keeapp-bd4e3',
    storageBucket: 'keeapp-bd4e3.appspot.com',
    iosClientId: '699424596579-hcejl7fltg7mhpl1m05jpoc1d2tvsl2d.apps.googleusercontent.com',
    iosBundleId: 'com.example.kee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlz4FAxteGTOaky8bPeyZ6XhqAzl4R8X0',
    appId: '1:699424596579:ios:0c01eaf99c225fd2ac4e56',
    messagingSenderId: '699424596579',
    projectId: 'keeapp-bd4e3',
    storageBucket: 'keeapp-bd4e3.appspot.com',
    iosClientId: '699424596579-n12ccbbb8o5ttpttd3ffl2d2tfjcem3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.kee.RunnerTests',
  );
}
